# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5cba9deb4edcb38020e4689448dcdbb301e9627ad93677084f224de8e16f8725f2c7c9bd590705c9c6cbdb143a6ac4427d11962d216aa6f37c06cbea39698c4

test:
  secret_key_base: 4faa00ddd934b781281643076d86ae48bb84f53504b278923acdb4b011bb5c697fd31cc21267fb7f876d03f1efe999c2b9c792e704bf94150a93917493ca9546

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
